# Generated by Django 4.0.4 on 2022-05-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название товара')),
                ('dates', models.DateField(verbose_name='Дата поступления')),
                ('price', models.IntegerField(max_length=64, verbose_name='Цена')),
                ('unit', models.CharField(max_length=2, verbose_name='Единица измерения')),
                ('name_supplier', models.CharField(max_length=64, verbose_name='Наименование поставщика')),
            ],
        ),
    ]
