# Generated by Django 4.0.4 on 2022-06-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название товара')),
                ('dates', models.DateField(verbose_name='Дата поступления')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('unit', models.CharField(choices=[('P', 'шт'), ('K', 'кг')], max_length=1, verbose_name='Единица измерения')),
                ('name_supplier', models.CharField(max_length=64, verbose_name='Наименование поставщика')),
            ],
            options={
                'verbose_name': 'Карточка товара',
                'verbose_name_plural': 'Карточки товаров',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_list', models.CharField(max_length=64, verbose_name='Раздел')),
                ('deleted', models.BooleanField(default=False)),
                ('product_catalog', models.ManyToManyField(to='catalogapp.productcatalog')),
            ],
            options={
                'verbose_name': 'Раздел товара',
                'verbose_name_plural': 'Разделы товаров',
            },
        ),
    ]
