# Generated by Django 4.0.4 on 2022-06-17 19:46

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0002_section_site'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='section',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
