# Generated by Django 4.0.4 on 2022-05-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0003_auto_20220529_2040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catalog',
            new_name='ProductCatalog',
        ),
    ]
