# Generated by Django 4.0.4 on 2022-06-19 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0003_alter_section_managers_productcatalog_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='deleted',
        ),
    ]
